# template

version: '2'

services:

    web:
      build: .
      command: python route.py
      environment:
        - DEBUG=False
        - MONGO_URL=db

    db:
      image: mongo
      command: mongod --smallfiles
