# development
# docker-compose

web:
  extends:
    file: common.yml
    service: web
  links:
    - db:db
  environment:
    - DEBUG=True

db:
  extends:
    file: common.yml
    service: db
  command: bash -c "mongod --smallfiles & mongorestore `ls -td1 /backup/*/ | tail -1`; wait"
  volumes:
   - ./backup:/backup
