web:
  build: .
  command: python route.py
  volumes:
   - .:/app
  links:
    - db:db
  ports:
   - "80:5000"

mornitor:
  build: .
  command: ./bin/cron
  volumes:
   - .:/app
  links:
    - db:db

db:
  image: mongo
  command: mongod --smallfiles
  ports:
   - "27017:27017"
