# development
# docker-compose
version: '2'

services:

    web:
      extends:
        file: common.yml
        service: web
      links:
        - db:db
      ports:
        - "5000:5000"
      environment:
        - DEBUG=True

    db:
      extends:
        file: common.yml
        service: db
      command: bash -c "mongod --smallfiles & mongorestore `ls -d1 /backup/*/ | tail -1`; wait"
      volumes:
       - ./backup:/backup
