# docker-compose -f production.yml

web:
  extends:
    file: common.yml
    service: web
  links:
    - db:db

db:
  extends:
    file: common.yml
    service: db

mornitor:
  build: .
  command: ./mornitor.py
  volumes:
   - .:/app
  links:
    - db:db
