# docker-compose -f production.yml

version: '2'

services:
    nginx:
      build:
        context: nginx
        dockerfile: Dockerfile
      restart: always
      depends_on:
        - web
      ports:
        - "4000:80"

    web:
      extends:
        file: common.yml
        service: web
      restart: always

    db:
      extends:
        file: common.yml
        service: db
      volumes:
        - mongo-data:/data/db
      restart: always

    mornitor:
      build: .
      command: ./mornitor.py
      restart: always

volumes:
  mongo-data:
    driver: local
